import turtle as t
import random
s= t.Screen()
s.bgcolor("black")
f= t.Turtle()
f.hideturtle()
f.speed(0)
f.pensize(2)
i=0
radius=random.randint(1,10)
def a1():
    for _ in range(36):
        f.penup()
        f.color('pink')
        f.goto(-600,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a2():
    for _ in range(36):
        f.penup()
        f.color('blue')
        f.goto(-500,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a3():
    for _ in range(36):
        f.penup()
        f.color('green')
        f.goto(-400,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a4():
    for _ in range(36):
        f.penup()
        f.color('red')
        f.goto(-300,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a5():
    for _ in range(36):
        f.penup()
        f.color('orange')
        f.goto(-200,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a6():
    for _ in range(36):
        f.penup()
        f.color('pink')
        f.goto(-100,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a7():
    for _ in range(36):
        f.penup()
        f.color('blue')
        f.goto(100,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a8():
    for _ in range(36):
        f.penup()
        f.color('green')
        f.goto(200,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a9():
    for _ in range(36):
        f.penup()
        f.color('red')
        f.goto(300,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a10():
    for _ in range(36):
        f.penup()
        f.color('orange')
        f.goto(400,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a11():
    for _ in range(36):
        f.penup()
        f.color('violet')
        f.goto(500,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def a12():
    for _ in range(36):
        f.penup()
        f.color('yellow')
        f.goto(600,-300)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(20)
        f.right(5)
        f.forward(10)
        f.backward(10)
def u(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(-400,200)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def u1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(-400,250)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)  
def r(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(-200,200)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def r1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(-200,250)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)  
def k(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(-100,100)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def k1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(-100,150)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)  
def p(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(100,100)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def p1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(100,150)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)  
def q(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(200,200)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def q1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(200,250)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)  
def v(radius):
    for i in range(10):
        t.circle(radius)
        radius=radius-4
        t.speed(0)
        t.penup()
        t.pensize(4)
        t.goto(400,200)
        t.pencolor(random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"]))
        t.pendown()
def v1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(400,250)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(50)
        f.right(15)
        f.forward(10)
        f.backward(30)
def wish():
     f.penup()
     f.color("white")
     f.goto(0,250)
     f.write('*HAPPY DIWALI*',align='center',font=('TimesNewRoman',25,'italic'))
     f.pendown()
def draw():
    f.penup()
    f.color("red")
    f.goto(0,-150)
    f.pendown()
    f.begin_fill()
    for _ in range(5):
        f.circle(15, 180)
        f.right(180)    
    f.end_fill()
def explosion():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(0, -150)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(100)
        f.right(45)
        f.forward(30)
        f.backward(130)
def ex1():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(-450,-10)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(100)
        f.right(45)
        f.forward(30)
        f.backward(130) 
def ex2():
    for _ in range(36):
        f.penup()
        f.color(color())
        f.goto(450,-10)
        f.pendown()
        f.setheading(_ * 10)
        f.forward(100)
        f.right(45)
        f.forward(30)
        f.backward(130)             
def color():
    return random.choice(["red", "orange", "yellow", "white", "purple", "green", "blue"])
def main():
    t.hideturtle()
    a1()
    a2()
    a3()
    a4()
    a5()
    a6()
    a7()
    a8()
    a9()
    a10()
    a11()
    a12()
    r(radius)
    r1()
    k(radius)
    k1()
    p(radius)
    p1()
    q(radius)
    q1()
    u(radius)
    u1()
    v(radius)
    v1()
    draw()
    explosion()
    ex1()
    ex2()
    wish()
    t.done()
main()